local mgr_module = {
	"player_mgr_module",
	"net_mgr_module",
	"equip_mgr_module",
	"schedule_mgr_module",
	"family_mgr_module",
	"arena_mgr_module",
}

local player_module = {
	"bag_module",
	"level_module",
	"player_module",
	"hunhuan_module",
	"spirit_module",
	"shenqi_qihe_module",
	"shenqi_strengthen_module",
	"shenqi_star_module",
	"equip_module",
	"neigong_module",
	"task_module",
	"tianfu_module",
	"wuhun_module",
	"grass_module",
	"baoxiang_module",
	"complex_module",
	"anqi_module",
	"lifeskill_module",
	"danyao_module",
	"wing_module",
	"element_bow_module",
	"vitality_module",
	"position_module",
	"achievement_module",
	"tujian_module",
	"relation_module",
	"team_module",
	"pay_module",
	"active_common_module",
	"family_module",
	"arena_module",
	"dress_module",
	"wartoken_module",
}

return {
	mgr_module = mgr_module,
	player_module = player_module,
}