require("util.msg_enum")

CTOL = {
	CTOL_NET_MSG = 1,
	CTOL_MSG = 2,
	CTOL_REMOVE_PLAYER = 3,
	CTOL_FRAME_UPDATE = 4,
}

LTOC = {
	LTOC_SEND_PLAYER_MSG = 1,
	LTOC_SEND_SERVER_MSG = 2,
	LTOC_SEND_SERVER_MSG_PACK = 3,
	LTOC_GEN_UNIQUE_ID = 4,
}